### ISSUE TITLE
FATAL SignalException: SIGTERM

### ISSUE THREAD

**Issue by jmuheim** [alexch/rerun#53]
I try to restart webrick whenever an important file changes. This is the output:

```
=> Booting WEBrick
=> Rails 4.0.3 application starting in development on http://0.0.0.0:3001
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
[2014-03-19 09:38:13] INFO  WEBrick 1.3.1
[2014-03-19 09:38:13] INFO  ruby 2.1.0 (2013-12-25) [x86_64-darwin12.0]
[2014-03-19 09:38:13] INFO  WEBrick::HTTPServer#start: pid=9912 port=3001
r09:38:31 [rerun] Restarting
09:38:31 [rerun] Sending signal TERM to 9912
[2014-03-19 09:38:31] FATAL SignalException: SIGTERM
    /Users/josh/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/webrick/server.rb:170:in `select'
    /Users/josh/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/webrick/server.rb:170:in `block in start'
    /Users/josh/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/webrick/server.rb:32:in `start'
    /Users/josh/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/webrick/server.rb:160:in `start'
    /Users/josh/.rvm/gems/ruby-2.1.0@base/gems/rack-1.5.2/lib/rack/handler/webrick.rb:14:in `run'
    /Users/josh/.rvm/gems/ruby-2.1.0@base/gems/rack-1.5.2/lib/rack/server.rb:264:in `start'
    /Users/josh/.rvm/gems/ruby-2.1.0@base/gems/railties-4.0.3/lib/rails/commands/server.rb:84:in `start'
    /Users/josh/.rvm/gems/ruby-2.1.0@base/gems/railties-4.0.3/lib/rails/commands.rb:76:in `block in <top (required)>'
    /Users/josh/.rvm/gems/ruby-2.1.0@base/gems/railties-4.0.3/lib/rails/commands.rb:71:in `tap'
    /Users/josh/.rvm/gems/ruby-2.1.0@base/gems/railties-4.0.3/lib/rails/commands.rb:71:in `<top (required)>'
    bin/rails:8:in `require'
    bin/rails:8:in `<main>'
[2014-03-19 09:38:31] INFO  going to shutdown ...
[2014-03-19 09:38:31] INFO  WEBrick::HTTPServer#start done.
```

I'm concerned about the "FATAL SignalException: SIGTERM": is this really correct? Webrick is reloaded correctly, but this looks a bit strange to me.

**Comment by alexch** [comment]
My guess is that it's a bug in Webrick that has been fixed sometime in the past 3-1/2 years :-) 

Another thing to try is using `bundle exec` in various places when running rerun and/or rails.

    bundle exec rerun -- bundle exec rails server

Yet another idea is to install `thin` instead of `webrick`; it seems more robust in my experience.
