### ISSUE TITLE
Trouble with new --restart option

### ISSUE THREAD

**Issue by mwpastore** [alexch/rerun#86]
I'm attempting to use the new `--restart` option and SIGUSR2 to reload Puma on changes (in development). Here's my invocation:

```shell
$ bundle exec rerun --restart --signal USR2 -- puma --debug
```

It starts up fine, but when I touch a file to trigger a restart, here's what happens:

```
10:10:41 [rerun] Change detected: 1 modified: config.ru
E, [2015-10-06T10:10:41.546640 #2670] ERROR -- : exception while processing events: undefined local variable or method `options' for #<Rerun::Runner:0x0055638e158730> Backtrace:
 -- /home/mwp/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rerun-b1312057ef1f/lib/rerun/runner.rb:64:in `restart'
 -- /home/mwp/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rerun-b1312057ef1f/lib/rerun/runner.rb:198:in `block in start'
 -- /home/mwp/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rerun-b1312057ef1f/lib/rerun/watcher.rb:65:in `call'
 -- /home/mwp/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rerun-b1312057ef1f/lib/rerun/watcher.rb:65:in `block (2 levels) in start'
 -- /home/mwp/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/listen-3.0.3/lib/listen/event/config.rb:23:in `call'
 -- /home/mwp/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/listen-3.0.3/lib/listen/event/config.rb:23:in `call'
 -- /home/mwp/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/listen-3.0.3/lib/listen/event/processor.rb:115:in `_process_changes'
 -- /home/mwp/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/listen-3.0.3/lib/listen/event/processor.rb:19:in `block in loop_for'
 -- /home/mwp/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/listen-3.0.3/lib/listen/event/processor.rb:15:in `loop'
 -- /home/mwp/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/listen-3.0.3/lib/listen/event/processor.rb:15:in `loop_for'
 -- /home/mwp/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/listen-3.0.3/lib/listen/event/loop.rb:84:in `_wait_for_changes'
 -- /home/mwp/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/listen-3.0.3/lib/listen/event/loop.rb:42:in `block in setup'
 -- /home/mwp/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/listen-3.0.3/lib/listen/internals/thread_pool.rb:6:in `call'
 -- /home/mwp/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/listen-3.0.3/lib/listen/internals/thread_pool.rb:6:in `block in add'
```

**Comment by mwpastore** [comment]
Here's a patch that seems to fix the issue:

```patch
diff --git a/lib/rerun/runner.rb b/lib/rerun/runner.rb
index a866767..b085ff1 100644
--- a/lib/rerun/runner.rb
+++ b/lib/rerun/runner.rb
@@ -61,7 +61,7 @@ module Rerun
     def restart
       @restarting = true
       if @options[:restart]
-        restart_with_signal(options[:signal])
+        restart_with_signal(@options[:signal])
       else
         stop
         start
```

I'll submit a PR.
